# Generated by Django 4.2.13 on 2024-06-13 16:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_type', models.CharField(choices=[('TOEIC_SCORE_300', 'TOEICスコア300レベル'), ('TOEIC_SCORE_600', 'TOEICスコア600レベル'), ('TOEIC_SCORE_900', 'TOEICスコア900レベル')], max_length=100)),
                ('level', models.CharField(choices=[('TOEIC_SCORE_300', 'TOEICスコア300レベル'), ('TOEIC_SCORE_600', 'TOEICスコア600レベル'), ('TOEIC_SCORE_900', 'TOEICスコア900レベル')], max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
