# Generated by Django 4.2.13 on 2024-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz_type',
            field=models.CharField(choices=[('Word', '単語'), ('Idiom', '熟語'), ('Sentence', '文章')], max_length=100),
        ),
    ]
