# Generated by Django 4.2.13 on 2024-06-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_exercise', '0002_alter_quizresult_quiz_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='user_id',
            new_name='user',
        ),
    ]
