# Generated by Django 4.2.13 on 2024-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_exercise', '0003_rename_user_id_quizresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz_type',
            field=models.CharField(choices=[('Word', '単語'), ('Idiom', '熟語'), ('Sentence', '文章'), ('LongReading', '長文読解')], max_length=100),
        ),
    ]
