# Generated by Django 4.2.13 on 2024-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_useractivatetokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='change_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
